### ISSUE TITLE
当页数很大时的样式问题。

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-pagination#17]
页数会互相挤在一起。

**Comment by ex90rts** [comment]
如图：
<img width="656" alt="screen shot 2017-06-05 at 8 16 39 pm" src="https://cloud.githubusercontent.com/assets/15277141/26783668/ef867fd8-4a2b-11e7-9a27-e6b31f0b871a.png">

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-pagination/commit/ad30836730f2b03492a13ac58a6ecdc6b183bf45
